// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type ApplyAddOnResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	// Successful response
	AppliedAddOn *shared.AppliedAddOn
	ContentType  string
	StatusCode   int
	RawResponse  *http.Response
}
