// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type DeleteCustomerRequest struct {
	// External ID of the existing customer
	ExternalID string `pathParam:"style=simple,explode=false,name=external_id"`
}

type DeleteCustomerResponse struct {
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	// Successful response
	Customer    *shared.Customer
	StatusCode  int
	RawResponse *http.Response
}
