// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type DeleteAppliedCouponRequest struct {
	// Applied Coupon Lago ID
	AppliedCouponID string `pathParam:"style=simple,explode=true,name=applied_coupon_id"`
	// External ID of the existing customer
	CustomerExternalID string `pathParam:"style=simple,explode=false,name=customer_external_id"`
}

type DeleteAppliedCouponResponse struct {
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Successful response
	AppliedCoupon *shared.AppliedCoupon
	ContentType   string
	StatusCode    int
	RawResponse   *http.Response
}
