// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type DestroyAddOnRequest struct {
	// Code of the existing add-on
	Code string `pathParam:"style=simple,explode=false,name=code"`
}

type DestroyAddOnResponse struct {
	// Successful response
	AddOn *shared.AddOn
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	StatusCode              int
	RawResponse             *http.Response
}
