// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type FinalizeInvoiceRequest struct {
	// ID of the draft Lago Invoice
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type FinalizeInvoiceResponse struct {
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	// Successful response
	Invoice     *shared.Invoice
	StatusCode  int
	RawResponse *http.Response
}
