// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type FindCouponRequest struct {
	// Code of the existing coupon
	Code string `pathParam:"style=simple,explode=false,name=code"`
}

type FindCouponResponse struct {
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	// Successful response
	Coupon      *shared.Coupon
	StatusCode  int
	RawResponse *http.Response
}
