// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type FindCustomerCurrentUsageRequest struct {
	// External ID of the existing customer
	CustomerExternalID string `pathParam:"style=simple,explode=false,name=customer_external_id"`
	// External subscription ID
	ExternalSubscriptionID string `queryParam:"style=form,explode=true,name=external_subscription_id"`
}

type FindCustomerCurrentUsageResponse struct {
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	// Successful response
	CustomerUsage *shared.CustomerUsage
	StatusCode    int
	RawResponse   *http.Response
}
