// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type GetCustomerPortalURLRequest struct {
	// External ID of the existing customer
	CustomerExternalID string `pathParam:"style=simple,explode=false,name=customer_external_id"`
}

type GetCustomerPortalURL200ApplicationJSONCustomer struct {
	PortalURL string `json:"portal_url"`
}

// GetCustomerPortalURL200ApplicationJSON - Successful response
type GetCustomerPortalURL200ApplicationJSON struct {
	Customer GetCustomerPortalURL200ApplicationJSONCustomer `json:"customer"`
}

type GetCustomerPortalURLResponse struct {
	// Forbidden
	APIResponseForbidden *shared.APIResponseForbidden
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	ContentType             string
	// Successful response
	GetCustomerPortalURL200ApplicationJSONObject *GetCustomerPortalURL200ApplicationJSON
	StatusCode                                   int
	RawResponse                                  *http.Response
}
