// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type UpdateCouponRequest struct {
	// Update an existing coupon
	CouponInput shared.CouponInput `request:"mediaType=application/json"`
	// Code of the existing coupon
	Code string `pathParam:"style=simple,explode=false,name=code"`
}

type UpdateCouponResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	ContentType                    string
	// Successful response
	Coupon      *shared.Coupon
	StatusCode  int
	RawResponse *http.Response
}
