// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type UpdateBillableMetricRequest struct {
	// Update an existing billable metric
	BillableMetricInput shared.BillableMetricInput `request:"mediaType=application/json"`
	// Code of the existing billable metric
	Code string `pathParam:"style=simple,explode=false,name=code"`
}

type UpdateBillableMetricResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	// Successful response
	BillableMetric *shared.BillableMetric
	ContentType    string
	StatusCode     int
	RawResponse    *http.Response
}
