// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type UpdateWalletRequest struct {
	// Update an existing wallet
	WalletUpdateInput shared.WalletUpdateInput `request:"mediaType=application/json"`
	// Lago ID of the existing wallet
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateWalletResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	ContentType                    string
	StatusCode                     int
	RawResponse                    *http.Response
	// Successful response
	Wallet *shared.Wallet
}
