// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type UpdateCreditNoteRequest struct {
	// Update an existing credit note
	CreditNoteUpdateInput shared.CreditNoteUpdateInput `request:"mediaType=application/json"`
	// Id of the existing credit note
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateCreditNoteResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	ContentType                    string
	// Successful response
	CreditNote  *shared.CreditNote
	StatusCode  int
	RawResponse *http.Response
}
