// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/lago-go/pkg/models/shared"
	"net/http"
)

type UpdateFeeRequest struct {
	// Payload to update a fee
	FeeUpdateInput *shared.FeeUpdateInput `request:"mediaType=application/json"`
	// ID of the existing Lago Fee
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateFeeResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	// Not Found error
	APIResponseNotFound *shared.APIResponseNotFound
	// Unauthorized error
	APIResponseUnauthorized *shared.APIResponseUnauthorized
	// Unprocessable entity error
	APIResponseUnprocessableEntity *shared.APIResponseUnprocessableEntity
	ContentType                    string
	// Successful response
	FeeObject   *shared.FeeObject
	StatusCode  int
	RawResponse *http.Response
}
