// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type AddOnObject struct {
	AmountCents    int64     `json:"amount_cents"`
	AmountCurrency string    `json:"amount_currency"`
	Code           string    `json:"code"`
	CreatedAt      time.Time `json:"created_at"`
	Description    *string   `json:"description,omitempty"`
	LagoID         string    `json:"lago_id"`
	Name           string    `json:"name"`
}
