// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseForbidden - Forbidden
type APIResponseForbidden struct {
	Code   string `json:"code"`
	Error  string `json:"error"`
	Status int    `json:"status"`
}
