// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseUnprocessableEntity - Unprocessable entity error
type APIResponseUnprocessableEntity struct {
	Code         string                 `json:"code"`
	Error        string                 `json:"error"`
	ErrorDetails map[string]interface{} `json:"error_details"`
	Status       int                    `json:"status"`
}
