// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseNotAllowed - Not Allowed error
type APIResponseNotAllowed struct {
	Code   string `json:"code"`
	Error  string `json:"error"`
	Status int    `json:"status"`
}
