// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseUnauthorized - Unauthorized error
type APIResponseUnauthorized struct {
	Error  string `json:"error"`
	Status int    `json:"status"`
}
