// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseNotFound - Not Found error
type APIResponseNotFound struct {
	Code   string `json:"code"`
	Error  string `json:"error"`
	Status int    `json:"status"`
}
