// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type AppliedAddOnObject struct {
	AddOnCode          string    `json:"add_on_code"`
	AmountCents        int64     `json:"amount_cents"`
	AmountCurrency     string    `json:"amount_currency"`
	CreatedAt          time.Time `json:"created_at"`
	ExternalCustomerID string    `json:"external_customer_id"`
	LagoAddOnID        string    `json:"lago_add_on_id"`
	LagoCustomerID     string    `json:"lago_customer_id"`
	LagoID             string    `json:"lago_id"`
}
