// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppliedCoupons - Successful response
type AppliedCoupons struct {
	AppliedCoupons []AppliedCouponObject `json:"applied_coupons"`
}
