// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppliedAddOn - Successful response
type AppliedAddOn struct {
	AppliedAddOn AppliedAddOnObject `json:"applied_add_on"`
}
