// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AppliedCouponInputAppliedCouponFrequencyEnum - Frequency type
type AppliedCouponInputAppliedCouponFrequencyEnum string

const (
	AppliedCouponInputAppliedCouponFrequencyEnumOnce      AppliedCouponInputAppliedCouponFrequencyEnum = "once"
	AppliedCouponInputAppliedCouponFrequencyEnumRecurring AppliedCouponInputAppliedCouponFrequencyEnum = "recurring"
)

func (e *AppliedCouponInputAppliedCouponFrequencyEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "once":
		fallthrough
	case "recurring":
		*e = AppliedCouponInputAppliedCouponFrequencyEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for AppliedCouponInputAppliedCouponFrequencyEnum: %s", s)
	}
}

type AppliedCouponInputAppliedCoupon struct {
	AmountCents        *int64  `json:"amount_cents,omitempty"`
	AmountCurrency     *string `json:"amount_currency,omitempty"`
	CouponCode         string  `json:"coupon_code"`
	ExternalCustomerID string  `json:"external_customer_id"`
	// Frequency type
	Frequency         *AppliedCouponInputAppliedCouponFrequencyEnum `json:"frequency,omitempty"`
	FrequencyDuration *int64                                        `json:"frequency_duration,omitempty"`
	PercentageRate    *float64                                      `json:"percentage_rate,omitempty"`
}

// AppliedCouponInput - Apply coupon payload
type AppliedCouponInput struct {
	AppliedCoupon AppliedCouponInputAppliedCoupon `json:"applied_coupon"`
}
