// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppliedCoupon - Successful response
type AppliedCoupon struct {
	AppliedCoupon AppliedCouponObject `json:"applied_coupon"`
}
