// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BatchEventInputEvent struct {
	Code                    string                 `json:"code"`
	ExternalCustomerID      *string                `json:"external_customer_id,omitempty"`
	ExternalSubscriptionIds []string               `json:"external_subscription_ids"`
	Properties              map[string]interface{} `json:"properties,omitempty"`
	Timestamp               *int64                 `json:"timestamp,omitempty"`
	TransactionID           string                 `json:"transaction_id"`
}

// BatchEventInput - Batch events payload
type BatchEventInput struct {
	Event BatchEventInputEvent `json:"event"`
}
