// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BillableMetric - Successful response
type BillableMetric struct {
	BillableMetric BillableMetricObject `json:"billable_metric"`
}
