// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BillableMetrics - Successful response
type BillableMetrics struct {
	BillableMetrics []BillableMetricObject `json:"billable_metrics"`
}
