// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type CouponInputCouponAppliesTo struct {
	PlanCodes []string `json:"plan_codes,omitempty"`
}

// CouponInputCouponCouponTypeEnum - Coupon type
type CouponInputCouponCouponTypeEnum string

const (
	CouponInputCouponCouponTypeEnumFixedAmount CouponInputCouponCouponTypeEnum = "fixed_amount"
	CouponInputCouponCouponTypeEnumPercentage  CouponInputCouponCouponTypeEnum = "percentage"
)

func (e CouponInputCouponCouponTypeEnum) ToPointer() *CouponInputCouponCouponTypeEnum {
	return &e
}

func (e *CouponInputCouponCouponTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fixed_amount":
		fallthrough
	case "percentage":
		*e = CouponInputCouponCouponTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CouponInputCouponCouponTypeEnum: %v", v)
	}
}

// CouponInputCouponExpirationEnum - Expiration type
type CouponInputCouponExpirationEnum string

const (
	CouponInputCouponExpirationEnumNoExpiration CouponInputCouponExpirationEnum = "no_expiration"
	CouponInputCouponExpirationEnumTimeLimit    CouponInputCouponExpirationEnum = "time_limit"
)

func (e CouponInputCouponExpirationEnum) ToPointer() *CouponInputCouponExpirationEnum {
	return &e
}

func (e *CouponInputCouponExpirationEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "no_expiration":
		fallthrough
	case "time_limit":
		*e = CouponInputCouponExpirationEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CouponInputCouponExpirationEnum: %v", v)
	}
}

// CouponInputCouponFrequencyEnum - Frequency type
type CouponInputCouponFrequencyEnum string

const (
	CouponInputCouponFrequencyEnumOnce      CouponInputCouponFrequencyEnum = "once"
	CouponInputCouponFrequencyEnumRecurring CouponInputCouponFrequencyEnum = "recurring"
)

func (e CouponInputCouponFrequencyEnum) ToPointer() *CouponInputCouponFrequencyEnum {
	return &e
}

func (e *CouponInputCouponFrequencyEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "once":
		fallthrough
	case "recurring":
		*e = CouponInputCouponFrequencyEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CouponInputCouponFrequencyEnum: %v", v)
	}
}

type CouponInputCoupon struct {
	AmountCents    *int64                      `json:"amount_cents,omitempty"`
	AmountCurrency *string                     `json:"amount_currency,omitempty"`
	AppliesTo      *CouponInputCouponAppliesTo `json:"applies_to,omitempty"`
	Code           *string                     `json:"code,omitempty"`
	// Coupon type
	CouponType *CouponInputCouponCouponTypeEnum `json:"coupon_type,omitempty"`
	// Expiration type
	Expiration   *CouponInputCouponExpirationEnum `json:"expiration,omitempty"`
	ExpirationAt *time.Time                       `json:"expiration_at,omitempty"`
	// Frequency type
	Frequency         *CouponInputCouponFrequencyEnum `json:"frequency,omitempty"`
	FrequencyDuration *int64                          `json:"frequency_duration,omitempty"`
	Name              *string                         `json:"name,omitempty"`
	PercentageRate    *float64                        `json:"percentage_rate,omitempty"`
	Reusable          *bool                           `json:"reusable,omitempty"`
}

// CouponInput - Coupon payload
type CouponInput struct {
	Coupon CouponInputCoupon `json:"coupon"`
}
