// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreditNote - Successful response
type CreditNote struct {
	CreditNote CreditNoteObject `json:"credit_note"`
}
