// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreditNoteItemObject struct {
	AmountCents    int64     `json:"amount_cents"`
	AmountCurrency string    `json:"amount_currency"`
	Fee            FeeObject `json:"fee"`
	LagoID         string    `json:"lago_id"`
}
