// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CreditNoteInputCreditNoteItems struct {
	AmountCents int64  `json:"amount_cents"`
	FeeID       string `json:"fee_id"`
}

// CreditNoteInputCreditNoteReasonEnum - Reason
type CreditNoteInputCreditNoteReasonEnum string

const (
	CreditNoteInputCreditNoteReasonEnumDuplicatedCharge      CreditNoteInputCreditNoteReasonEnum = "duplicated_charge"
	CreditNoteInputCreditNoteReasonEnumProductUnsatisfactory CreditNoteInputCreditNoteReasonEnum = "product_unsatisfactory"
	CreditNoteInputCreditNoteReasonEnumOrderChange           CreditNoteInputCreditNoteReasonEnum = "order_change"
	CreditNoteInputCreditNoteReasonEnumOrderCancellation     CreditNoteInputCreditNoteReasonEnum = "order_cancellation"
	CreditNoteInputCreditNoteReasonEnumFraudulentCharge      CreditNoteInputCreditNoteReasonEnum = "fraudulent_charge"
	CreditNoteInputCreditNoteReasonEnumOther                 CreditNoteInputCreditNoteReasonEnum = "other"
)

func (e *CreditNoteInputCreditNoteReasonEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "duplicated_charge":
		fallthrough
	case "product_unsatisfactory":
		fallthrough
	case "order_change":
		fallthrough
	case "order_cancellation":
		fallthrough
	case "fraudulent_charge":
		fallthrough
	case "other":
		*e = CreditNoteInputCreditNoteReasonEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for CreditNoteInputCreditNoteReasonEnum: %s", s)
	}
}

type CreditNoteInputCreditNote struct {
	CreditAmountCents int64                            `json:"credit_amount_cents"`
	Description       *string                          `json:"description,omitempty"`
	InvoiceID         string                           `json:"invoice_id"`
	Items             []CreditNoteInputCreditNoteItems `json:"items"`
	// Reason
	Reason            CreditNoteInputCreditNoteReasonEnum `json:"reason"`
	RefundAmountCents int64                               `json:"refund_amount_cents"`
}

// CreditNoteInput - Credit note payload
type CreditNoteInput struct {
	CreditNote CreditNoteInputCreditNote `json:"credit_note"`
}
