// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreditNotes - Successful response
type CreditNotes struct {
	CreditNotes []CreditNoteObject `json:"credit_notes"`
}
