// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type CustomerMetadataObject struct {
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	DisplayInInvoice *bool      `json:"display_in_invoice,omitempty"`
	Key              *string    `json:"key,omitempty"`
	LagoID           *string    `json:"lago_id,omitempty"`
	Value            *string    `json:"value,omitempty"`
}
