// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type CustomerUsageObject struct {
	AmountCents         int64               `json:"amount_cents"`
	AmountCurrency      string              `json:"amount_currency"`
	ChargesUsage        []ChargeUsageObject `json:"charges_usage"`
	FromDatetime        time.Time           `json:"from_datetime"`
	IssuingDate         time.Time           `json:"issuing_date"`
	ToDatetime          time.Time           `json:"to_datetime"`
	TotalAmountCents    int64               `json:"total_amount_cents"`
	TotalAmountCurrency string              `json:"total_amount_currency"`
	VatAmountCents      int64               `json:"vat_amount_cents"`
	VatAmountCurrency   string              `json:"vat_amount_currency"`
}
