// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CustomerUsage - Successful response
type CustomerUsage struct {
	CustomerUsage CustomerUsageObject `json:"customer_usage"`
}
