// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EventEstimateFeesInputEvent struct {
	Code                   string                 `json:"code"`
	ExternalCustomerID     *string                `json:"external_customer_id,omitempty"`
	ExternalSubscriptionID *string                `json:"external_subscription_id,omitempty"`
	Properties             map[string]interface{} `json:"properties,omitempty"`
}

// EventEstimateFeesInput - Event payload for instant fee estimate
type EventEstimateFeesInput struct {
	Event EventEstimateFeesInputEvent `json:"event"`
}
