// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type EventObject struct {
	Code                   string                 `json:"code"`
	CreatedAt              time.Time              `json:"created_at"`
	ExternalCustomerID     string                 `json:"external_customer_id"`
	ExternalSubscriptionID string                 `json:"external_subscription_id"`
	LagoCustomerID         string                 `json:"lago_customer_id"`
	LagoID                 string                 `json:"lago_id"`
	LagoSubscriptionID     string                 `json:"lago_subscription_id"`
	Properties             map[string]interface{} `json:"properties,omitempty"`
	Timestamp              time.Time              `json:"timestamp"`
	TransactionID          string                 `json:"transaction_id"`
}
