// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FeesPaginated - Successful response
type FeesPaginated struct {
	Fees []FeeObject    `json:"fees"`
	Meta PaginationMeta `json:"meta"`
}
