// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GroupObject struct {
	Key    string `json:"key"`
	LagoID string `json:"lago_id"`
	Value  string `json:"value"`
}
