// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GroupPropertiesObject struct {
	GroupID string                 `json:"group_id"`
	Values  map[string]interface{} `json:"values"`
}
