// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InvoiceInputInvoiceMetadata struct {
	ID    *string `json:"id,omitempty"`
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// InvoiceInputInvoicePaymentStatusEnum - Status
type InvoiceInputInvoicePaymentStatusEnum string

const (
	InvoiceInputInvoicePaymentStatusEnumPending   InvoiceInputInvoicePaymentStatusEnum = "pending"
	InvoiceInputInvoicePaymentStatusEnumSucceeded InvoiceInputInvoicePaymentStatusEnum = "succeeded"
	InvoiceInputInvoicePaymentStatusEnumFailed    InvoiceInputInvoicePaymentStatusEnum = "failed"
)

func (e InvoiceInputInvoicePaymentStatusEnum) ToPointer() *InvoiceInputInvoicePaymentStatusEnum {
	return &e
}

func (e *InvoiceInputInvoicePaymentStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "succeeded":
		fallthrough
	case "failed":
		*e = InvoiceInputInvoicePaymentStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvoiceInputInvoicePaymentStatusEnum: %v", v)
	}
}

type InvoiceInputInvoice struct {
	Metadata []InvoiceInputInvoiceMetadata `json:"metadata,omitempty"`
	// Status
	PaymentStatus InvoiceInputInvoicePaymentStatusEnum `json:"payment_status"`
}

// InvoiceInput - Update an existing invoice
type InvoiceInput struct {
	Invoice InvoiceInputInvoice `json:"invoice"`
}
