// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Organization - Successful response
type Organization struct {
	Organization OrganizationObject `json:"organization"`
}
