// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginationMeta struct {
	// Current page
	CurrentPage int64 `json:"current_page"`
	// Next page
	NextPage *int64 `json:"next_page,omitempty"`
	// Previous page
	PrevPage *int64 `json:"prev_page,omitempty"`
	// Total number of records
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}
