// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// SubscriptionCreateInputSubscriptionBillingTimeEnum - Billing time
type SubscriptionCreateInputSubscriptionBillingTimeEnum string

const (
	SubscriptionCreateInputSubscriptionBillingTimeEnumCalendar    SubscriptionCreateInputSubscriptionBillingTimeEnum = "calendar"
	SubscriptionCreateInputSubscriptionBillingTimeEnumAnniversary SubscriptionCreateInputSubscriptionBillingTimeEnum = "anniversary"
)

func (e *SubscriptionCreateInputSubscriptionBillingTimeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "calendar":
		fallthrough
	case "anniversary":
		*e = SubscriptionCreateInputSubscriptionBillingTimeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionCreateInputSubscriptionBillingTimeEnum: %s", s)
	}
}

type SubscriptionCreateInputSubscription struct {
	// Billing time
	BillingTime        *SubscriptionCreateInputSubscriptionBillingTimeEnum `json:"billing_time,omitempty"`
	ExternalCustomerID string                                              `json:"external_customer_id"`
	ExternalID         string                                              `json:"external_id"`
	Name               *string                                             `json:"name,omitempty"`
	PlanCode           string                                              `json:"plan_code"`
	SubscriptionAt     *time.Time                                          `json:"subscription_at,omitempty"`
}

// SubscriptionCreateInput - Subscription payload
type SubscriptionCreateInput struct {
	Subscription SubscriptionCreateInputSubscription `json:"subscription"`
}
