// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Subscriptions - Successful response
type Subscriptions struct {
	Subscriptions []SubscriptionObject `json:"subscriptions"`
}
