// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// SubscriptionObjectBillingTimeEnum - Billing time
type SubscriptionObjectBillingTimeEnum string

const (
	SubscriptionObjectBillingTimeEnumCalendar    SubscriptionObjectBillingTimeEnum = "calendar"
	SubscriptionObjectBillingTimeEnumAnniversary SubscriptionObjectBillingTimeEnum = "anniversary"
)

func (e SubscriptionObjectBillingTimeEnum) ToPointer() *SubscriptionObjectBillingTimeEnum {
	return &e
}

func (e *SubscriptionObjectBillingTimeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "calendar":
		fallthrough
	case "anniversary":
		*e = SubscriptionObjectBillingTimeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionObjectBillingTimeEnum: %v", v)
	}
}

// SubscriptionObjectStatusEnum - Subscription status
type SubscriptionObjectStatusEnum string

const (
	SubscriptionObjectStatusEnumActive     SubscriptionObjectStatusEnum = "active"
	SubscriptionObjectStatusEnumPending    SubscriptionObjectStatusEnum = "pending"
	SubscriptionObjectStatusEnumTerminated SubscriptionObjectStatusEnum = "terminated"
	SubscriptionObjectStatusEnumCanceled   SubscriptionObjectStatusEnum = "canceled"
)

func (e SubscriptionObjectStatusEnum) ToPointer() *SubscriptionObjectStatusEnum {
	return &e
}

func (e *SubscriptionObjectStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "pending":
		fallthrough
	case "terminated":
		fallthrough
	case "canceled":
		*e = SubscriptionObjectStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionObjectStatusEnum: %v", v)
	}
}

type SubscriptionObject struct {
	// Billing time
	BillingTime        SubscriptionObjectBillingTimeEnum `json:"billing_time"`
	CanceledAt         *time.Time                        `json:"canceled_at,omitempty"`
	CreatedAt          time.Time                         `json:"created_at"`
	DowngradePlanDate  *time.Time                        `json:"downgrade_plan_date,omitempty"`
	ExternalCustomerID string                            `json:"external_customer_id"`
	ExternalID         string                            `json:"external_id"`
	LagoCustomerID     string                            `json:"lago_customer_id"`
	LagoID             string                            `json:"lago_id"`
	Name               *string                           `json:"name,omitempty"`
	NextPlanCode       *string                           `json:"next_plan_code,omitempty"`
	PlanCode           string                            `json:"plan_code"`
	PreviousPlanCode   *string                           `json:"previous_plan_code,omitempty"`
	StartedAt          time.Time                         `json:"started_at"`
	// Subscription status
	Status         SubscriptionObjectStatusEnum `json:"status"`
	SubscriptionAt time.Time                    `json:"subscription_at"`
	TerminatedAt   *time.Time                   `json:"terminated_at,omitempty"`
}
