// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type SubscriptionUpdateInputSubscription struct {
	Name           *string    `json:"name,omitempty"`
	SubscriptionAt *time.Time `json:"subscription_at,omitempty"`
}

// SubscriptionUpdateInput - Update an existing subscription
type SubscriptionUpdateInput struct {
	Subscription SubscriptionUpdateInputSubscription `json:"subscription"`
}
