// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Subscription - Successful response
type Subscription struct {
	Subscription SubscriptionObject `json:"subscription"`
}
