// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WalletInputWallet struct {
	Currency           string     `json:"currency"`
	ExpirationAt       *time.Time `json:"expiration_at,omitempty"`
	ExternalCustomerID string     `json:"external_customer_id"`
	GrantedCredits     *float64   `json:"granted_credits,omitempty"`
	Name               *string    `json:"name,omitempty"`
	PaidCredits        *float64   `json:"paid_credits,omitempty"`
	RateAmount         float64    `json:"rate_amount"`
}

// WalletInput - Wallet payload
type WalletInput struct {
	Wallet *WalletInputWallet `json:"wallet,omitempty"`
}
