// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WalletTransactions - Successful response
type WalletTransactions struct {
	WalletTransactions []WalletTransactionObject `json:"wallet_transactions"`
}
