// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WalletUpdateInputWallet struct {
	ExpirationAt *time.Time `json:"expiration_at,omitempty"`
	Name         *string    `json:"name,omitempty"`
}

// WalletUpdateInput - Update an existing wallet
type WalletUpdateInput struct {
	Wallet WalletUpdateInputWallet `json:"wallet"`
}
