// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WalletTransactionInputWalletTransaction struct {
	GrantedCredits *float64 `json:"granted_credits,omitempty"`
	PaidCredits    *float64 `json:"paid_credits,omitempty"`
	WalletID       string   `json:"wallet_id"`
}

// WalletTransactionInput - Wallet transaction payload
type WalletTransactionInput struct {
	WalletTransaction WalletTransactionInputWalletTransaction `json:"wallet_transaction"`
}
